---
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: ${HOME}/data/db
